name: seg-fault-backend
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=1.0.8
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - expat=2.5.0
  - libffi=3.4.2
  - libsqlite=3.40.0
  - libzlib=1.2.13
  - openssl=1.1.1t
  - pip=22.3.1
  - pypy=7.3.11
  - pypy3.9=7.3.11
  - python=3.9.16
  - python_abi=3.9
  - setuptools=65.6.3
  - sqlite=3.40.1
  - tk=8.6.12
  - tzdata=2022g
  - ucrt=10.0.20348.0
  - vc=14.2
  - vs2015_runtime=14.34.31931
  - wheel=0.37.1
  - wincertstore=0.2
  - xz=5.2.10
  - zlib=1.2.13
  - pip:
      - click==8.1.3
      - colorama==0.4.6
      - flask==2.2.3
      - importlib-metadata==6.0.0
      - itsdangerous==2.1.2
      - jinja2==3.1.2
      - markupsafe==2.1.2
      - randomtimestamp==2.2
      - werkzeug==2.2.3
      - zipp==3.13.0
